<center><h1> Create dummy data </h1></center>

## Which data do we need?
    1. Table events:
    event_id | event_name | event_address | event_start_date | event_end_date | event_start_time | event_end_time
    
    2. Table users:
    user_prename | user_name | user_email | user_alias | user_password | ticket_id | user_id | event_id
    
    3. Table pickups:
    pickup_cities | pickup_zip_code
    
    4. Table journey:
    event_address | pickup_zip_code | user_id | journey_id | journey_empty_spaces | journey_car | event_id | journey_text | journey_date | event_date | journey_start_time | event_start_time
    
    5. Table tickets:
    event_id | ticket_id | event_date

In [1]:
# --------------- creds --------------- 
import uuid # random unique IDs
import pandas as pd # Dataframes
from faker import Faker # create random data
from random import randint # random numbers for creation of test data

In [2]:
# --------------- table events ---------------
table_events = pd.DataFrame({
    "event_id" : ["2ab60824-b539-4a1f-ae1a-f7d94d2d55bb",
                 "7be626b0-c1cd-4a26-a111-60afb13ba940",
                 "eff7e9ae-9c58-42e1-8835-0d51c33dc480",
                 "e6930b99-e8ca-49f8-9583-89f54366dc14"],
    "event_name" : ["Time Warp",
                   "MAYDAY",
                   "Rock am Ring",
                   "World Club Dome"],
    "event_address" : ["Xaver-Fuhr-Straße 101, 68163 Mannheim", # this format is not good!
                      "Rheinlanddamm 200, 44139 Dortmund",
                      "Otto-Flimm-Straße, 53520 Nürburg",
                      "Mörfelder Landstraße 362, 60528 Frankfurt am Main"],
    "event_start_date" : ["2020-04-04",
                         "2020-04-30",
                         "2020-06-05",
                         "2020-06-05"],
    "event_end_date" : ["2020-04-05",
                       "2020-05-01",
                       "2020-06-07",
                       "2020-06-07"],
    "event_start_time" : ["19:00:00",
                         "17:00:00",
                         "12:00:00",
                         "20:00:00"],
    "event_end_time" : ["14:00:00",
                       "12:00:00",
                       "20:00:00",
                       "18:00:00"]
})
table_events.to_csv("table_events.csv", index=False)
table_events

,event_id,event_name,event_address,event_start_date,event_end_date,event_start_time,event_end_time
0,2ab60824-b539-4a1f-ae1a-f7d94d2d55bb,Time Warp,"Xaver-Fuhr-Straße 101, 68163 Mannheim",2020-04-04,2020-04-05,19:00:00,14:00:00
1,7be626b0-c1cd-4a26-a111-60afb13ba940,MAYDAY,"Rheinlanddamm 200, 44139 Dortmund",2020-04-30,2020-05-01,17:00:00,12:00:00
2,eff7e9ae-9c58-42e1-8835-0d51c33dc480,Rock am Ring,"Otto-Flimm-Straße, 53520 Nürburg",2020-06-05,2020-06-07,12:00:00,20:00:00
3,e6930b99-e8ca-49f8-9583-89f54366dc14,World Club Dome,"Mörfelder Landstraße 362, 60528 Frankfurt am Main",2020-06-05,2020-06-07,20:00:00,18:00:00

In [3]:
# --------------- table tickets ---------------
table_tickets = []
for i in range(1, 401):
    x = randint(0, len(table_events)-1)
    table_tickets.append({
        "event_id" : table_events["event_id"][x],
        "ticket_id" : uuid.uuid4(),
        "event_start_date" : table_events["event_start_date"][x],
        "event_end_date" : table_events["event_end_date"][x]
    })
table_tickets = pd.DataFrame(table_tickets)
table_tickets = table_tickets[["event_id", "ticket_id", "event_start_date", "event_end_date"]]
table_tickets.to_csv("table_tickets.csv", index=False)
table_tickets

,event_id,ticket_id,event_start_date,event_end_date
0,eff7e9ae-9c58-42e1-8835-0d51c33dc480,8799f347-d288-47ee-90e7-e560e2657fbf,2020-06-05,2020-06-07
1,eff7e9ae-9c58-42e1-8835-0d51c33dc480,d8519876-1a45-4662-ad97-1b29f31e1aae,2020-06-05,2020-06-07
2,eff7e9ae-9c58-42e1-8835-0d51c33dc480,bda3b016-7f0b-42c5-9ee2-c55856563260,2020-06-05,2020-06-07
3,2ab60824-b539-4a1f-ae1a-f7d94d2d55bb,254be047-7781-4a7b-945a-2d9b05bce36d,2020-04-04,2020-04-05
4,7be626b0-c1cd-4a26-a111-60afb13ba940,10b0326e-ff5f-43d4-a02c-54c71938f527,2020-04-30,2020-05-01
...,...,...,...,...
395,2ab60824-b539-4a1f-ae1a-f7d94d2d55bb,b6b3c725-6d45-49d2-a13d-0f281b458da1,2020-04-04,2020-04-05
396,eff7e9ae-9c58-42e1-8835-0d51c33dc480,0fdda772-0c58-4e2f-b8eb-38fa7eef7601,2020-06-05,2020-06-07
397,e6930b99-e8ca-49f8-9583-89f54366dc14,de8dbc02-cd9b-4f2c-bda0-c2acbdf03bca,2020-06-05,2020-06-07
398,7be626b0-c1cd-4a26-a111-60afb13ba940,cd5bc60c-1add-4e6f-94a1-fd7d6512b0d1,2020-04-30,2020-05-01
399,eff7e9ae-9c58-42e1-8835-0d51c33dc480,215ec89b-463e-466d-b1c8-042219debe58,2020-06-05,2020-06-07

In [4]:
# --------------- table users ---------------
table_user = []
faker = Faker(["de_DE"])

for i in range(1, 101):
    x = randint(0, len(table_tickets)-1)
    table_user.append({
        "user_id": uuid.uuid4(),
        "user_prename" : faker.first_name(),
        "user_name" : faker.last_name(),
        "user_email" : faker.email(),
        "user_alias" : faker.user_name(),
        "user_password" : faker.password(),
        "ticket_id" : table_tickets["ticket_id"][x],
        "event_id" : table_tickets["event_id"][x],
        })

table_user = pd.DataFrame(table_user)
table_user = table_user[["user_id", "user_prename", "user_name", "user_email", "user_alias", "user_password", "ticket_id", 
                        "event_id"]]
table_user.to_csv("table_user.csv", index=False)
table_user

,user_id,user_prename,user_name,user_email,user_alias,user_password,ticket_id,event_id
0,b3a37c80-d6c5-4cd5-8623-17342d44c310,Heribert,Junk,giesela18@web.de,natalie34,@6A!eBq5zi,cbf82dcd-371c-4707-a513-0215d5e74714,eff7e9ae-9c58-42e1-8835-0d51c33dc480
1,4cb6721c-4eed-450e-89d2-12c1c038f7ba,Bayram,Bohnbach,olenaaustermuehle@gmail.com,meik30,KQJhKnH8#6,b52afbf5-6a57-4d48-9064-09030836ec52,2ab60824-b539-4a1f-ae1a-f7d94d2d55bb
2,457a1681-cf3a-4324-b80d-f14d31d7e6c7,Ingried,Scheuermann,heiko20@web.de,torben18,&6EB8ot%#G,2df35fd0-d063-4ecb-8b32-0a4c46e21427,eff7e9ae-9c58-42e1-8835-0d51c33dc480
3,5e6ee605-d152-4f4a-a822-8617f48db313,Slawomir,Johann,christopher37@gmail.com,mariokuhl,N7cUFnl!@a,c3534a25-ad12-4422-a9ee-c79da8883c67,2ab60824-b539-4a1f-ae1a-f7d94d2d55bb
4,838277b3-488d-4b89-8ad3-7a49526a86ca,Wilhelmine,Nerger,andersmarkus@web.de,nicolas46,@4x4K9ZxJo,328a28c6-45e8-4f0e-b221-1f1e83f76c2b,2ab60824-b539-4a1f-ae1a-f7d94d2d55bb
...,...,...,...,...,...,...,...,...
95,98776c4f-0b70-403a-972e-da3df6cc26c8,Nikolaos,Geisler,dietzgoran@bohnbach.net,milka55,Aq5TR_RsD*,7bcd2636-761b-4027-b86e-50e18c5323cb,e6930b99-e8ca-49f8-9583-89f54366dc14
96,0553f8b8-233a-4507-bab9-36d7e0b58ed8,Willibald,Liebelt,rosl43@junck.de,uadolph,@$q6FUfl9D,5c7ee52c-3eff-4c60-bb0c-9dc262cbd372,e6930b99-e8ca-49f8-9583-89f54366dc14
97,534db7fe-5988-4bc8-8061-b398b75090b8,Marko,Nette,burkardmude@web.de,czorbach,$%aP^YZo39,cb5a9faf-4079-4e8d-9a00-a1b570014366,e6930b99-e8ca-49f8-9583-89f54366dc14
98,6efdb7a1-f789-4434-a1a3-c4739eb6481d,Paul,Nerger,heinz-juergenrogner@weitzel.com,ekaester,^K5LvlApc9,fe6949fb-d569-40b2-8fe9-1a1624f47b75,eff7e9ae-9c58-42e1-8835-0d51c33dc480
99,9b49f405-1570-4944-880c-7b11e52344e8,Heidi,Geisel,hartmannhenni@web.de,ewesack,8*2xKJMgEC,f3ab44c5-f693-46a2-86f1-bd009197f491,eff7e9ae-9c58-42e1-8835-0d51c33dc480

In [5]:
# --------------- table_pickups ---------------
table_pickups = pd.read_csv("D:/TechTalents/project-tt-app/server/German-Zip-Codes.csv", sep = ";")
table_pickups = table_pickups[["Ort", "Plz"]]
table_pickups = table_pickups.rename(columns={"Ort" : "pickup_city", "Plz": "pickup_zip_code"})
table_pickups = table_pickups.dropna()
table_pickups["pickup_zip_code"] = table_pickups["pickup_zip_code"].astype(int)
table_pickups.to_csv("table_pickups.csv", index=False)
table_pickups

         pickup_city  pickup_zip_code
0               Aach            54298
1               Aach            78267
2             Aachen            52062
3             Aachen            52064
4             Aachen            52066
...              ...              ...
19669    Zwingenberg            69439
19670  Zwischendeich            19322
19671        Zwochau             4509
19672        Zwönitz             8297
19673          Zwota             8267

[19670 rows x 2 columns]

In [6]:
# --------------- table_journey ---------------
table_journey = []
car_manufactures = ["Abarth","Alfa Romeo","Aston Martin","Audi","Bentley","BMW","Bugatti","Cadillac","Chevrolet","Chrysler",
                    "Citroën","Dacia","Daewoo","Daihatsu","Dodge","Donkervoort","DS","Ferrari","Fiat","Fisker","Ford",
                    "Honda","Hummer","Hyundai","Infiniti","Iveco","Jaguar","Jeep","Kia","KTM","Lada","Lamborghini",
                    "Lancia","Land Rover","Landwind","Lexus","Lotus","Maserati","Maybach","Mazda","McLaren","Mercedes-Benz",
                    "MG","Mini","Mitsubishi","Morgan","Nissan","Opel","Peugeot","Porsche","Renault","Rolls-Royce","Rover",
                    "Saab","Seat","Skoda","Smart","SsangYong","Subaru","Suzuki","Tesla","Toyota","Volkswagen","Volvo"]
for i in range(1, 301):
    x = randint(0, len(table_events)-1)
    y = randint(0, len(table_pickups)-1)
    z = randint(0, len(table_user)-1)
    a = randint(0, len(car_manufactures)-1)
    table_journey.append({
        "event_address" : table_events["event_address"][x],
        "event_id" : table_events["event_id"][x],
        "event_start_date" : table_events["event_start_date"][x],
        "event_start_time" : table_events["event_start_time"][x],
        "pickup_zip_code" : table_pickups["pickup_zip_code"][y],
        "user_id": table_user["user_id"][z],
        "journey_id": uuid.uuid4(),
        "journey_empty_spaces": randint(1, 5),
        "journey_car": car_manufactures[a],
        "journey_text": faker.text(),
        "journey_date": table_events["event_start_date"][x],
        "journey_start_time": faker.time()
    })
table_journey = pd.DataFrame(table_journey)
table_journey.to_csv("table_journey.csv", index=False)
table_journey

,event_address,event_id,event_start_date,event_start_time,pickup_zip_code,user_id,journey_id,journey_empty_spaces,journey_car,journey_text,journey_date,journey_start_time
0,"Xaver-Fuhr-Straße 101, 68163 Mannheim",2ab60824-b539-4a1f-ae1a-f7d94d2d55bb,2020-04-04,19:00:00,64579,239afb50-63ac-4046-b247-cc603537df4d,544d8404-ba3d-4d7e-929c-02be1b208309,1,Maserati,Voluptatibus sunt nemo labore. Pariatur assume...,2020-04-04,06:00:15
1,"Mörfelder Landstraße 362, 60528 Frankfurt am Main",e6930b99-e8ca-49f8-9583-89f54366dc14,2020-06-05,20:00:00,26897,9b49f405-1570-4944-880c-7b11e52344e8,0d2766c5-0d53-47d3-94e4-eaf5ec823b43,3,Rolls-Royce,Illo rem veniam cupiditate ratione delectus ne...,2020-06-05,20:35:37
2,"Xaver-Fuhr-Straße 101, 68163 Mannheim",2ab60824-b539-4a1f-ae1a-f7d94d2d55bb,2020-04-04,19:00:00,41836,3c8c8503-7bc9-4991-8dfd-c11ed29fecf1,2bcb47bf-2960-434f-a221-01ca99004782,3,Alfa Romeo,Libero enim consectetur dolore a quis vitae. Q...,2020-04-04,20:37:09
3,"Otto-Flimm-Straße, 53520 Nürburg",eff7e9ae-9c58-42e1-8835-0d51c33dc480,2020-06-05,12:00:00,14548,39276af3-6366-430d-bc34-e7f7ce5622fe,f4af1907-6265-413a-8ebd-b631aeac526b,4,Skoda,Corporis itaque consequuntur. Minima harum sap...,2020-06-05,19:17:38
4,"Mörfelder Landstraße 362, 60528 Frankfurt am Main",e6930b99-e8ca-49f8-9583-89f54366dc14,2020-06-05,20:00:00,36419,0a3ceb74-068c-4e58-befd-e63b756a58c3,d171af25-6c71-4c4b-80a9-62fce061290c,5,Infiniti,Et aperiam commodi corrupti quo. Error invento...,2020-06-05,06:20:11
...,...,...,...,...,...,...,...,...,...,...,...,...
295,"Otto-Flimm-Straße, 53520 Nürburg",eff7e9ae-9c58-42e1-8835-0d51c33dc480,2020-06-05,12:00:00,34537,bdd4a3ae-0585-44dc-9253-c1575dd920f6,5059bb9e-3cab-46b5-8f70-f7b128e13dda,4,Opel,Possimus hic aut. Exercitationem aut quas hic ...,2020-06-05,10:23:31
296,"Xaver-Fuhr-Straße 101, 68163 Mannheim",2ab60824-b539-4a1f-ae1a-f7d94d2d55bb,2020-04-04,19:00:00,37136,55c7a81d-2e4e-4356-be03-82034b2edbaf,6fdbe09b-9648-4431-b731-ac3ec575b7a9,5,Fisker,Facilis et cumque expedita deserunt exercitati...,2020-04-04,05:57:40
297,"Mörfelder Landstraße 362, 60528 Frankfurt am Main",e6930b99-e8ca-49f8-9583-89f54366dc14,2020-06-05,20:00:00,1561,2448380d-cfe7-4e57-86dd-1f87c65a154f,2486f12f-4212-466d-9cd9-53deca0f1312,4,Chevrolet,Quos expedita architecto. Occaecati eveniet re...,2020-06-05,12:03:53
298,"Otto-Flimm-Straße, 53520 Nürburg",eff7e9ae-9c58-42e1-8835-0d51c33dc480,2020-06-05,12:00:00,19294,a58ad0a2-93fc-4194-8aaf-7c9708d42460,96ef9c3c-b8e0-4765-b3d4-0fb77d8097cd,2,Fiat,Odio animi dicta deleniti. Nesciunt ratione de...,2020-06-05,10:01:27
299,"Rheinlanddamm 200, 44139 Dortmund",7be626b0-c1cd-4a26-a111-60afb13ba940,2020-04-30,17:00:00,22926,eb785f3e-2342-4495-97a4-e253cfa84322,caec6357-42f3-4b30-aa3c-9e7db3d1ea60,1,Daewoo,Saepe dolor facilis quam. Explicabo repellat a...,2020-04-30,07:12:36